### ISSUE TITLE
border color consistency

### ISSUE THREAD

**Issue by larxx** [benjaminbenais/copilot-theme#1]
I'm really digging this theme, great job! However, something that really bothers me is that inconsistent color of the tab border and the activity border.  Maybe just stick with one color so that it'll look more coherent and better.

<img width="983" alt="Screen Shot 2021-07-09 at 8 30 01 PM" src="https://user-images.githubusercontent.com/76559183/125078343-d67b9f00-e0f4-11eb-9c72-0662a1843ad9.png">

**Comment by benjaminbenais** [comment]
Hi, thanks for the feedback.

You're right the yellow looks better on the activity bar. I'm not sure about the buttons and checkbox, it's less subtle that 
way. Another option for the buttons/checkbox is a light grey but it looks a bit sad and less readable. Any thoughts ?

All yellow:
<img width="1440" alt="Screenshot 2021-07-09 at 14 43 58" src="https://user-images.githubusercontent.com/45941603/125080421-1165de80-e0c5-11eb-8878-6cdcffc9bfeb.png">

light grey:
<img width="1440" alt="Screenshot 2021-07-09 at 14 57 41" src="https://user-images.githubusercontent.com/45941603/125081410-43c40b80-e0c6-11eb-819f-4be12bad5d44.png">

**Comment by benjaminbenais** [comment]
Hi, thanks for the feedback. You're right it look better with the same color. I've made the change and you can download the latest version :)
