### ISSUE TITLE
ISSUE URGENT

### ISSUE THREAD

**Issue by Adatta1276** [benjaminbenais/copilot-theme#3]
The theme's pretty cool, **but the yellow bit of it is a bit overwhelming**, _perhaps you could make it light blue instead?_

**Comment by benjaminbenais** [comment]
Hi, can you share screenshots of the overwhelming yellow parts ? Also make sure to use the latest version (0.0.6), I've replaced the yellow by a light grey to soften the theme a bit.

**Comment by Adatta1276** [comment]
Here it is : 

![overwhelmingly yellow](https://user-images.githubusercontent.com/73747859/125201504-1bd2d480-e28d-11eb-9a39-8d8ade9ab04c.png)

Using version 0.0.7 though (the latest version I found)
