### ISSUE TITLE
`not` keyword not being rendered 

### ISSUE THREAD

**Issue by Kwieeciol** [benjaminbenais/copilot-theme#4]
It seems that the `not` keyword is being ignored in pretty much all languages

Ruby:
![image](https://user-images.githubusercontent.com/64413721/126125495-f6e3bdfa-8d31-435b-9499-35317753b39a.png)

Python:
![image](https://user-images.githubusercontent.com/64413721/126125533-e9220ec0-03f7-4754-ab5a-c314fcca6c61.png)

Shouldn't it be syntax highlighted like any other keyword?

EDIT: Other themes seem to work and highlight the keyword

Ruby:
![image](https://user-images.githubusercontent.com/64413721/126144381-73d4d6ff-e5a6-4ef9-bbb6-44919c7b149d.png)

Python
![image](https://user-images.githubusercontent.com/64413721/126144271-bb971ea0-8775-482d-a8f8-56016e9b158d.png)

**Comment by benjaminbenais** [comment]
Hi, thanks for pointing this out.

I've made the fix (see screenshots). You should be able to update in few minutes.

<img width="358" alt="logical-op-rb" src="https://user-images.githubusercontent.com/45941603/126160006-b225794b-ce6a-4ff2-9541-0a25f623a511.png">
<img width="359" alt="logical-op-py" src="https://user-images.githubusercontent.com/45941603/126160012-7268b7d4-76fa-47f2-8883-decdf452bd44.png">

**Comment by Kwieeciol** [comment]
Thanks a lot! Seems to work, love the theme:)
