### ISSUE TITLE
Sidebar buttons hover/selected colour

### ISSUE THREAD

**Issue by mo-gaafar** [benjaminbenais/copilot-theme#7]
It is white instead of cyan 

![image](https://user-images.githubusercontent.com/46086535/162057436-0afd9807-7981-40f1-99fc-4abb26788988.png)
Should be:
![image](https://user-images.githubusercontent.com/46086535/162058458-1cd70ff1-41ff-431c-8fd2-889633a6961f.png)

**Comment by benjaminbenais** [comment]
Fixed in 1.0.0
